FROM nvcr.io/nvidia/cuda:12.0.0-runtime-ubuntu22.04

# docker build . -t sd_app -f .docker/Dockerfile-prod
# docker run -it --gpus all sd_app
# docker run -it --gpus all sd_app sleep infinity (for test only)

# Install python 3.10 on the CUDA docker image.
#ENV PATH /usr/local/bin:$PATH # Already the runtime image have it.
ENV LANG C.UTF-8

RUN apt-get update
RUN apt-get install -y --no-install-recommends python3.10
RUN apt-get install -y --no-install-recommends python3-pip
RUN rm -rf /var/lib/apt/lists/*
RUN apt-get clean

ENV GPG_KEY A035C8C19219BA821ECEA86B64E628F8D684696D
ENV PYTHON_VERSION 3.10.9

RUN mkdir wd
WORKDIR /wd

COPY requirements.txt .
RUN pip3 install -r requirements.txt

ENV LOGGING_LEVEL=FATAL

COPY . .
CMD python3 src/main.py